### ISSUE TITLE
SQLite output not working as expected

### ISSUE THREAD

**Issue by emory** [darkoperator/dnsrecon#187]
hi, thank you very much for the fix for CSV output!

now i'm working on a different project and i'd like to use the sqlite database output, but when i try to do so i get this error:

```
[*] Saving records to SQLite3 file: MyDB.db
Traceback (most recent call last):
  File "./dnsrecon.py", line 1763, in <module>
    main()
  File "./dnsrecon.py", line 1746, in main
    write_db(results_db, returned_records)
  File "./dnsrecon.py", line 774, in write_db
    if re.match(r'PTR|^[A]$|AAAA', n['type']):
TypeError: list indices must be integers or slices, not str
```

i'm using `3.27.2 2019-02-25 16:06:06 bd49a8271d650fa89e446b42e513b595a717b9212c91dd384aab871fc1d0alt1` and dnsrecon version `0.10.1` and i did a `git pull` before beginning my session but i was still current from the last commit.

my Pi has sqlite `2.8.17` and that sqlite3 above - after i get that error i can use `sqlite3 MyDB.db` but it doesn't have any findings in the data table.

**Comment by L1ghtn1ng** [comment]
Can you please run the command lsb_release -a and share the output
________________________________
From: Emory L. ***@***.***>
Sent: Tuesday, May 4, 2021 8:07:44 PM
To: darkoperator/dnsrecon ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [darkoperator/dnsrecon] SQLite output not working as expected (#187)


hi, thank you very much for the fix for CSV output!

now i'm working on a different project and i'd like to use the sqlite database output, but when i try to do so i get this error:

[*] Saving records to SQLite3 file: MyDB.db
Traceback (most recent call last):
  File "./dnsrecon.py", line 1763, in <module>
    main()
  File "./dnsrecon.py", line 1746, in main
    write_db(results_db, returned_records)
  File "./dnsrecon.py", line 774, in write_db
    if re.match(r'PTR|^[A]$|AAAA', n['type']):
TypeError: list indices must be integers or slices, not str


i'm using 3.27.2 2019-02-25 16:06:06 bd49a8271d650fa89e446b42e513b595a717b9212c91dd384aab871fc1d0alt1 and dnsrecon version 0.10.1 and i did a git pull before beginning my session but i was still current from the last commit.

my Pi has sqlite 2.8.17 and that sqlite3 above - after i get that error i can use sqlite3 MyDB.db but it doesn't have any findings in the data table.

**Comment by emory** [comment]
```
emory@raspi03 ~ % lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by L1ghtn1ng** [comment]
I am not to sure what is going on, will have a look at this on the weekend if I get time but I would say for now make sure you are using a virtualenv for dnsrecon and see if that fixes your issue?

**Comment by L1ghtn1ng** [comment]
Think it might be down to the fact that sqlite in butster is old and that might be why? Have you tried it on ubuntu by any chance?

**Comment by L1ghtn1ng** [comment]
Timeout
