### ISSUE TITLE
-n nameserver option not supporting name, only IPs

### ISSUE THREAD

**Issue by FabioPedretti** [darkoperator/dnsrecon#217]
And it errors:

```
# ./dnsrecon.py -d google.com -n ns1.google.com
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 982, in nameservers
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/dnsrecon/./dnsrecon.py", line 7, in <module>
    __main__.main()
  File "/home/test/dnsrecon/dnsrecon/cli.py", line 1558, in main
    if check_nxdomain_hijack(entry):
  File "/home/test/dnsrecon/dnsrecon/cli.py", line 209, in check_nxdomain_hijack
    res.nameservers = [nameserver]
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 984, in nameservers
    raise ValueError(f'nameserver {nameserver} is not an '
ValueError: nameserver ns1.google.com is not an IP address or valid https URL
```

**Comment by L1ghtn1ng** [comment]
This is not a dnsrecon issue it's a dnspython issue

**Comment by hlein** [comment]
It looks to me like this is intended to be supported?

Starting around https://github.com/darkoperator/dnsrecon/blame/master/dnsrecon/cli.py#L1557, we iterate over the nameserver argument(s). Line 1565 seems to be resolving provided nameserver hostnames to IPs:
```
            # Resolve in the case if FQDN
            answer = socket_resolv(entry)
```
...The problem is the quoted error is thrown when `entry` is used first thing in the loop, line 1558, before it has been resolved. It makes sense that you can't tell your DNS library to use a hostname to send requests to, since... it needs to have an IP to send to. Should the resolve check simply be moved earlier in the for loop? Or if there's no intention to support `--name_servers` arguments of hostnames, dnsrecon could reject them with a cleaner error message, and probably `s/Domain server to use/Domain server IP to use/` in the usage, as well.

**Comment by L1ghtn1ng** [comment]
More than happy to except a PR if you would like to contribute a fix?

On 23 Apr 2022, at 23:04, hlein ***@***.***> wrote:

﻿

It looks to me like this is intended to be supported?

Starting around https://github.com/darkoperator/dnsrecon/blame/master/dnsrecon/cli.py#L1557, we iterate over the nameserver argument(s). Line 1565 seems to be resolving provided nameserver hostnames to IPs:

            # Resolve in the case if FQDN
            answer = socket_resolv(entry)


...The problem is the quoted error is thrown when entry is used first thing in the loop, line 1558, before it has been resolved. It makes sense that you can't tell your DNS library to use a hostname to send requests to, since... it needs to have an IP to send to. Should the resolve check simply be moved earlier in the for loop? Or if there's no intention to support --name_servers arguments of hostnames, dnsrecon could reject them with a cleaner error message, and probably s/Domain server to use/Domain server IP to use/ in the usage, as well.

**Comment by darkoperator** [comment]
Normally in a pentest/redteam on tests each individual name server, that is why when I wrote the tool made it and tested it with ip addresses in mind. Should probably document that as a best practice to avoid using a FQDN since one may hit different name servers and makes it harder to do repeatable validation.

**Comment by L1ghtn1ng** [comment]
Thanks for the input Carlos

On 23 Apr 2022, at 23:43, Carlos Perez ***@***.***> wrote:

﻿

Normally in a pentest/redteam on tests each individual name server, that is why when I wrote the tool made it and tested it with ip addresses in mind. Should probably document that as a best practice to avoid using a FQDN since one may hit different name servers and makes it harder to do repeatable validation.

**Comment by hlein** [comment]
> More than happy to except a PR if you would like to contribute a fix?

Sure, I'll try to get to it and/or assign an intern to it :)

My inclination would be to go ahead and support expanding a name to IP(s), like the code currently seems to try to do. But if the preference is to only support IPs in light of @darkoperator's comment, and to make relevant usage/error updates, please let me know.

**Comment by L1ghtn1ng** [comment]
The usage and error updates would be good 😊

On 24 Apr 2022, at 01:04, hlein ***@***.***> wrote:

﻿

More than happy to except a PR if you would like to contribute a fix?

Sure, I'll try to get to it and/or assign an intern to it :)

My inclination would be to go ahead and support expanding a name to IP(s), like the code currently seems to try to do. But if the preference is to only support IPs in light of @darkoperator<https://github.com/darkoperator>'s comment, and to make relevant usage/error updates, please let me know.
