### ISSUE TITLE
Feature Request - Ability to Feed in a list of domains to perform DNS record enumeration against

### ISSUE THREAD

**Issue by TheBigStonk** [darkoperator/dnsrecon#264]
**Feature Request or Bug or Other**
Feature Request 

**Describe the feature request or bug or other**
Would be keen to get something that works similar to `-iL` in which we could feed in a list of domains, and then from there perform the standard stuff DNS enumeration already does in a synchronous order, before outputting the results to console or listed logically in outputted XML,CSV,JSON

**Expected behaviour**
Potentially a method of being able to feed in a list of domains or subdomains, and output the results allowing for mass enumeration of targets.

Happy to try and POC up this and PR but wanted to check with you all first before the time commitment

**Comment by L1ghtn1ng** [comment]
Sounds like a great feature to add ☺️ am happy with this.

On 20 Mar 2024, at 03:50, TheBigStonk ***@***.***> wrote:

﻿

Feature Request or Bug or Other
Feature Request

Describe the feature request or bug or other
Would be keen to get something that works similar to -iL in which we could feed in a list of domains, and then from there perform the standard stuff DNS enumeration already does in a synchronous order, before outputting the results to console or listed logically in outputted XML,CSV,JSON

Expected behaviour
Potentially a method of being able to feed in a list of domains or subdomains, and output the results allowing for mass enumeration of targets.

Happy to try and POC up this and PR but wanted to check with you all first before the time commitment

**Comment by McFacePunch** [comment]
@L1ghtn1ng can you close this one?

**Comment by L1ghtn1ng** [comment]
Done
